In [1]:
import tensorflow as tf

C:\Users\User\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
hi = tf.constant('hello')
hi

<tf.Tensor 'Const:0' shape=() dtype=string>

In [3]:
sess = tf.Session()
sess.run( hi )

b'hello'

#### 텐서플로우를 이용한 간단한 계산

- 덧셈

In [4]:
# 상수 정의
a = tf.constant( 1234 )
b = tf.constant( 5000 )
a, b

(<tf.Tensor 'Const_1:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_2:0' shape=() dtype=int32>)

In [5]:
# 계산 정의
add_op = a + b
add_op
# <tf.Tensor 'add:0' shape=() dtype=int32>

# 한번 더 run
# <tf.Tensor 'add_1:0' shape=() dtype=int32>

<tf.Tensor 'add:0' shape=() dtype=int32>

In [ ]:
# 텐서플로우는 덧셈이라는 계산을 정의만 할 뿐
# 변수 app_op에 대입되는 것은
# 덧셈의 결과로 나오는 상수가 아니라
# '데이터 플로우 그래프'라는 객체이다

In [6]:
# 세션 시작
sess = tf.Session()

In [7]:
# 계산 처리는 파이썬이 하지 않고
# 파이썬 외부 즉, 텐서플로우에서 진행
# 계산 처리는 그래프라는 객체를 구축하고
# 이러한 그래프를 텐서플로우가 실행하면서 데이터가 흘러가는 구조
res = sess.run( add_op )
res, type(res)

(6234, numpy.int32)

#### 텐서플로우의 기본 항목

- 핵심 데이터 구조 요소 3개
 > 상수(constant)  
 > 변수(Variable)  
 > placeholder  

In [8]:
# 상수 정의
a = tf.constant( 120, name = 'a' )
b = tf.constant( 130, name = 'b' )
c = tf.constant( 140, name = 'c' )

a, b, c

(<tf.Tensor 'a:0' shape=() dtype=int32>,
 <tf.Tensor 'b:0' shape=() dtype=int32>,
 <tf.Tensor 'c:0' shape=() dtype=int32>)

In [9]:
# 변수 정의
v = tf.Variable(0, name = 'v')
v, v.name

Instructions for updating:
Colocations handled automatically by placer.


(<tf.Variable 'v:0' shape=() dtype=int32_ref>, 'v:0')

In [10]:
# 데이터 플로우 그래프 정의
calc_op = a + b + c
calc_op

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [11]:
# 변수에 값을 대입 → 데이터 플로우 그래프
assign_op = tf.assign( v, calc_op )
assign_op

<tf.Tensor 'Assign:0' shape=() dtype=int32_ref>

In [12]:
# 세션 실행
sess = tf.Session()
sess.run( assign_op )

390

In [13]:
# 변수값 출력하기 → 세션 수행을 통해서 확인
v, sess.run(v)

(<tf.Variable 'v:0' shape=() dtype=int32_ref>, 390)

In [ ]:
# placeholder
# - 쿼리 수행할 때, '?' 기호 같은 느낌
# - 데이터 플로우 그래프 구축 시, 값을 넣지 않고 값을 담을 수 있는 형태의 그릇만 만드는 형식
# → 세션이 수행될 때 값을 넣어서 실행
# 템플릿과 유사하게 값을 넣어두는 공간을 만드는 기능

In [14]:
# 정수형 데이터 3개를 담을 수 있는 그릇(배열 이용) 준비
# → placeholder를 준비
a = tf.placeholder( tf.int32, [3] )
a

<tf.Tensor 'Placeholder:0' shape=(3,) dtype=int32>

In [15]:
# 상수
b = tf.constant(2)

In [17]:
# 데이터 플로우 그래프
# 배열 * 값 → 행렬 * 값 → 벡터 * 스칼라
x2_op = a*b
x2_op

<tf.Tensor 'mul_1:0' shape=(3,) dtype=int32>

In [18]:
sess = tf.Session()

In [19]:
# 수행
# feed_dict는 placeholder에 값을 채운다
r1 = sess.run( x2_op, feed_dict={ a:[1, 2, 3] } )
r1

array([2, 4, 6])

#### 배열의 크기를 가변으로 처리하여 구성

In [20]:
# None을 넣으면 가변 처리가 되서,
# 배열의 개수는 가변적으로 대입 가능
# placeholder 정의
a = tf.placeholder( tf.int32, [None] )
a

<tf.Tensor 'Placeholder_1:0' shape=(?,) dtype=int32>

In [21]:
# 상수 정의
b = tf.constant(10)
b

<tf.Tensor 'Const_4:0' shape=() dtype=int32>

In [22]:
# 데이터 플로우 그래프 정의
x10_op = a*b

In [23]:
sess = tf.Session()

In [24]:
sess.run( x10_op, feed_dict={ a : [1, 2, 3, 4, 5] } )

array([10, 20, 30, 40, 50])

In [25]:
sess.run( x10_op, feed_dict={ a : [10, 20] } )

array([100, 200])